version: '3.7'
services:
  nginx:
    image: hls-streaming
    build:
      context: .
    ports:
      - 3001:80
    volumes:
      - './public/videos:/usr/share/nginx/html/videos'
    restart: always
